# Generated by Django 4.1.2 on 2022-11-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courses_names",
            options={
                "verbose_name": "Название курса",
                "verbose_name_plural": "Название курсов",
            },
        ),
        migrations.AddField(
            model_name="courses_names",
            name="picture_url",
            field=models.CharField(
                default="static/main/img/noimage_detail.png",
                max_length=1000,
                verbose_name="Ссылка обложку",
            ),
        ),
        migrations.AlterField(
            model_name="courses_names",
            name="description_text",
            field=models.TextField(default="Описания нет", verbose_name="Описание"),
        ),
    ]
