# Generated by Django 4.1.2 on 2022-12-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_courses_names_picture_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses_names",
            name="courses_url",
            field=models.CharField(
                default="courses",
                max_length=1000,
                verbose_name="Ссылка на основную страницу",
            ),
        ),
    ]
