# Generated by Django 4.1.2 on 2022-12-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_course_articles_course_articles_modulues"),
    ]

    operations = [
        migrations.AlterModelTable(name="course_articles", table="course_article",),
        migrations.AlterModelTable(
            name="course_articles_modulues", table="article_module",
        ),
        migrations.AlterModelTable(name="courses_names", table="course_name",),
    ]
