# Generated by Django 4.1.2 on 2022-12-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_course_articles_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course_articles_modulues",
            name="picture_url",
            field=models.CharField(
                default=None, max_length=1000, verbose_name="Ссылка на обложку"
            ),
        ),
    ]
