# Generated by Django 4.1.2 on 2022-12-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_alter_course_articles_modulues_picture_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="course_articles",
            name="article_url",
            field=models.CharField(
                default="home_course", max_length=1000, verbose_name="Ссылка на статью"
            ),
        ),
        migrations.AlterField(
            model_name="course_articles_modulues",
            name="picture_url",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="Ссылка на рисунок"
            ),
        ),
    ]
