# Generated by Django 4.1.2 on 2022-12-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_alter_course_articles_modulues_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course_articles_modulues",
            options={
                "verbose_name": "Глава статьи",
                "verbose_name_plural": "Главы статьей",
            },
        ),
        migrations.AddField(
            model_name="course_articles_modulues",
            name="picture_description",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="Название рисунока"
            ),
        ),
    ]
