# Generated by Django 4.1.2 on 2022-12-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_alter_course_articles_modulues_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course_articles_modulues",
            name="video_url",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="Ссылка на рисунок"
            ),
        ),
    ]
